### PR TITLE
Adapted notebooks to cate 3.0.1dev1

### PR DESCRIPTION
**Pull request by AliceBalfanz**
Notebooks are adapted to work with cate 3.0.1dev1 which is now based on xcube 0.9.1

@strawpants Would you mind running the NBs in the https://cate-lab.brockmann-consult.de for testing? 

I have not fixed the links about binder yet, is that something you could do, or should I ?
FYI, @TonioF is searching for a solution to include the git repo directly in the Hub, so user don't have to upload it manually.

### CODE REVIEW

**Comment by strawpants** [comment]
Hi @AliceBalfanz ,

I'm looking into the Greenland exercise right now it seems that it only works with the zarr-store version (older version of the data). The versions on odp results in all-nans on the variable `GMB_trend` from the call:
`
greenTrnd = open_dataset(ds_id=dataset_id, data_store_id=cci_store)
`
And that is the reason nothing is plotted.

So it seems that the data are somehow not correctly read into an xarray. (maybe from the normalization applied by cate?)

Besides this I don't have much time for testing the other exercises to be honest. @TonioF successfully updated the binder environment last time, so I guess he will be able to that more quickly than I can.

Roelof

**Review by strawpants — COMMENTED** [review]
Partial review. Some exercises have not been tested yet, and binder environment still needs to be tuned to use the right cate version? Is it an idea that Tonio has a look at the binder env and approve?

**Comment by TonioF** [comment]
Hi, I have updated the binder environment and tested with the SEAICE notebook. Worked smoothly.

**Review by strawpants — APPROVED** [review]
Cheers

**Pull request merged**
